### PR TITLE
Try another path to watchbot-progress

### LINKED ISSUE #131: watchbot-progress command not available with yarn
It appears the `watchbot-progress` executable is not available when installing ecs-watchbog with `yarn install`. The [`bin` command](https://github.com/mapbox/ecs-watchbot/blob/3b024444400667f6da4c5219de4dfa302bd96681/package.json#L28) in ecs-watchbot points to a node_modules tree reflected by npm installs, not yarn installs.

Sounds like a quick solution could be to use `path.resolve` for the watchbot-progress command and building it that way.

cc @rclark @GretaCB @mcwhittemore

### PR DESCRIPTION
**Pull request by rclark**
Attempting to fix #131 

cc @mapsam

### CODE REVIEW

**Comment by mapsam** [comment]
Looks like this doesn't do it fully @rclark. It finds the module just fine, but then that module's requires are off somehow:

```
Error: Cannot find module 'meow'
```

**Comment by rclark** [comment]
This worked for me in the following setup:

```
> mkdir yarned && cd yarned
> npm init
> npm install --save https://github.com/mapbox/ecs-watchbot/tarball/rabbit-hole
> rm -rf node_modules && yarn --ignore-engines --no-lockfile
> ./node_modules/.bin/watchbot-progress --help

  Tracks the progress of a distributed map-reduce operation

  USAGE: watchbot-progress <command> <job-id> [options]

  Environment variable $ProgressTable must be set as the ARN for the DynamoDB
  table that is used to track progress.

  COMMANDS:
    - status: check the status of a job
    - set-total: set the total number of parts in a job
    - set-metadata: set arbitrary metadata on the job record
    - complete-part: complete a single part
    - fail-job: mark a job as a failure
    - reduce-sent: mark a job as having its reduce step taken

  OPTIONS:
    -t, --total     (for set-total) the total number of parts in a job
    -p, --part      (for complete-part or status) the part number to mark as complete or check for completeness
    -m, --metadata  (for set-metadata) the JSON metadata object to store
    -r, --reason    (for fail-job) a description of why the job failed
```

**Comment by mapsam** [comment]
@rclark this is working as expected! Happy to merge and release.

**Comment by rclark** [comment]
Go for it!

**Pull request merged**
