### PR TITLE
Adds pagination for describeContainerInstances

### PR DESCRIPTION
**Pull request by emilymdubois**
Refs https://github.com/mapbox/ecs-watchbot/issues/62

This PR adds pagination for describeContainerInstances by [piggy-backing off the pagination already occurring for listContainerInstances](https://github.com/mapbox/ecs-watchbot/blob/93a3c4b59b51d87beb1baeb06b4cc572289a036e/lib/resources.js#L19-L28).

The test that's causing the 🏄  of errors is the [resource polling error test](https://github.com/mapbox/ecs-watchbot/blob/93a3c4b59b51d87beb1baeb06b4cc572289a036e/test/main.test.js#L312-L322). I can't quite figure out what's preventing the [finish event](https://github.com/mapbox/ecs-watchbot/blob/93a3c4b59b51d87beb1baeb06b4cc572289a036e/test/main.test.js#L316) from firing, since it looks like the [end function](https://github.com/mapbox/ecs-watchbot/blob/93a3c4b59b51d87beb1baeb06b4cc572289a036e/lib/main.js#L202-L204) is being called. Nothing jumps out to me immediately, but perhaps some seasoned eyes can spot something I'm missing.

cc @rclark

### CODE REVIEW

**Comment by rclark** [comment]
I think the problem is that in this test case the `HasInstances` event never emits. This prevents the main watchbot loop from cycling. `main.end()` does get called, but then another iteration through the loop never starts. Once one does, it'll pick up that it is supposed to shut down and emit the `finish`.

**Comment by emilymdubois** [comment]
That makes sense, thanks @rclark! I restructured the test so that it [makes its assertion about log contents after 1.8s](https://github.com/mapbox/ecs-watchbot/blob/080f7dd0428df03a9c10f79f379b43e6e9546118/test/main.test.js#L317-L322) instead of waiting for the `finish` event.

Do you think [this is an appropriate order of operations](https://github.com/mapbox/ecs-watchbot/blob/080f7dd0428df03a9c10f79f379b43e6e9546118/lib/resources.js#L41-L43) (i.e., that the `HasInstances` never fires and halts the main loop if there's an ECS error either with listing or describing container instances)?

**Comment by rclark** [comment]
The loop is going to be blocked until the `HasInstances` event fires **and** there are instances in the `status.instances` array. This is fine. The scenario that comes up in the test here is totally bizzaro / not real-life like we talked about yesterday.

**Comment by emilymdubois** [comment]
👍 Sounds good @rclark! Let me know if you have any reservations about me merging this. Otherwise, I'll merge, wait for https://github.com/mapbox/ecs-watchbot/pull/74, and roll a new release.

cc @mapsam

**Comment by mapsam** [comment]
#74 merged - apologies for the cruft!

**Comment by jacquestardie** [comment]
Just checking in, this hasn't been made it into a release yet, correct? If it hasn't, I'm happy to grab!

**Comment by rclark** [comment]
@jacquestardie -- @emilymdubois is also trying to wrap #75 into the next ecs-watchbot release.

**Pull request merged**
